var changing_map = [{
"1_1" : "The dragon remains beneath the surface. Do not act.",
"1_2" : "The dragon climbs to the surface. Seek advice from an authority you respect.",
"1_3" : "The Superior Person builds by day and remains vigilant through the night. Danger, but he will persevere.",
"1_4" : "The flying dragon hovers over the chasm from which he was born.",
"1_5" : "The dragon rises high for all to see. He has become the mentor he always longed to find.",
"1_6" : "Even a dragon may fly too high.",
"2_1" : "When frost crunches underfoot can winter ice be far behind?",
"2_2" : "Straight, square, and true. By being instead of doing, nothing is left undone.",
"2_3" : "Hide your brilliance. Feeling no threat, they won't resist the completion of your goal. All you lose is credit for the accomplishment.",
"2_4" : "Be a tied-up sack, letting your inner contents remain unseen. There will be no praise, but also no blame.",
"2_5" : "A yellow robe. Supreme good fortune.",
"2_6" : "The battling dragons are too evenly matched. Each spills black and yellow blood to the soil below",
"3_1" : "You have run up against an obstacle at the very head of the trail. Keep to your course. Seek mutual aid.",
"3_2" : "Her horses rear in fright; but the highwayman means no harm. He seeks only the hand of the maiden. She must refuse him, for she fears a very long journey lies ahead before she can marry.",
"3_3" : "A hunter who pursues his prey without a guide will lose his way in the deeps of the forest. The Superior Person knows his limitations and gives up the chase. To advance brings regret.",
"3_4" : "Her horses break away. Turning back, she must learn to trust, and accept the escort of her spurned highwayman. What seemed at first misfortune will lead to marriage.",
"3_5" : "He could rescue them, if only they would trust. For now, he must provide protection and small comfort from the shadows.",
"3_6" : "The horses break free. If the need for aid goes unrecognized, tears and blood will flow",
"4_1" : "A little discipline will make the fool sit up and take notice. Afterwards, the matter should be dropped, or some will question which is the master and which the fool.",
"4_2" : "The man is gentle with the misguided and understands the hearts of women. Such a one can be trusted with the kingdom.",
"4_3" : "No one respects a lovestruck woman who throws herself at the object of her desire. Do not idolize.",
"4_4" : "You are so terrified of being wrong, you leave no room for learning what is right.",
"4_5" : "Like a wide-eyed child, you wholly and naively trust the goodness of others. Such honor brings out their best.",
"4_6" : "The best way to prove a fool wrong is to let him have his way. To severely restrict his folly will invite him to always believe that his way would have been right.",
"5_1" : "No trouble in sight, but vague anxieties about what lies beyond the horizon. Whether real or not, the threat has already won your peace of mind.",
"5_2" : "Taking your post in the sand, ceaselessly watching the far shore for enemy movements, you must endure the taunts and contempt of your comrades. Good fortune in the end.",
"5_3" : "Anxiety prods you to premature action. Wading into the river, you become mired in the bed of mud. Not only does the enemy realize you detect them, but they see your vulnerability as an opportunity to strike.",
"5_4" : "The enemy is upon you. You wait in blood, preparing yourself for their blows; but your own ability can see you through, if you stand your ground and maintain balance.",
"5_5" : "You smile and join in the banquet, relaxing and gaining perspective, yet vigilant and prepared for the next onslaught. Such genuine grace under pressure ensures victory and good fortune.",
"5_6" : "The showdown comes, with the opponents too evenly matched. Just as all hopes of survival are dashed, three strangers appear. They will tip the scales in favor of the contender who recognizes them for what they are",
"6_1" : "No quarrel will blossom, unless you let your pride fertilize this budding conflict. Let the one who insults you expose himself for what he is. Don't fight this battle until you've already won it.",
"6_2" : "Knowing his comrades would be annihilated against their much stronger foe, he orders a full retreat, retires into seclusion, and is condemned by the very neighbors he saved from ruin.",
"6_3" : "He stands on his integrity, no matter what ill winds may blast him. Stand or fall, in the end he will remain exactly who he is.",
"6_4" : "Realizing the very root of conflict lies within his own heart, he lays down his arms and resolves to accept the things he cannot change.",
"6_5" : "Bring the conflict before a just authority. If you are truly in the right, justice will bring good fortune.",
"6_6" : "You can certainly win this conflict. Such a victory, though, will bring a lifetime of defending your prize against thieves and challengers",
"7_1" : "Knowing neither purpose nor direction, the soldiers march blindly onward.",
"7_2" : "The general marches with his soldiers, sharing their fate, good or bad, facing the consequences of his own decisions. For this he is loved and trusted by all.",
"7_3" : "A wagonload of corpses this way comes.",
"7_4" : "It is never a mistake to retreat to a stronger position.",
"7_5" : "The seasoned veteran is elevated to command, and none too soon. For the game is in the field, and it would be wise to catch it.",
"7_6" : "The victor divides the spoils among the loyal, leaving the jackals with neither reward nor obligation",
"8_1" : "Confidently and sincerely seeking union. His devotion to you and to truth makes this alliance correct. Unexpected good fortune.",
"8_2" : "Devotion comes from deep inside you. Good fortune if you keep to your course.",
"8_3" : "You are seeking union with unworthy people.",
"8_4" : "You express your devotion humbly and openly. Good fortune if you keep to this course.",
"8_5" : "The hunter surrounds the game on only three sides, allowing an avenue of escape. In seeking allegiance with others, leave room for them to say 'no'; this way, those choosing to join you will be sincere.",
"8_6" : "Without a head, the union cannot hold together. Misfortune",
"9_1" : "He turns back to his proper course. No harm done. In fact, good fortune comes of this return.",
"9_2" : "He lets himself be drawn back. Good fortune.",
"9_3" : "The spokes burst out of a wagon wheel, stopping the couple's journey. The man and wife waste time and energy blaming each other, causing major damage to their love instead of fixing the minor damage to the wagon.",
"9_4" : "By gaining confidence, the man keeps control of the conflict, avoiding the blood that could be spilled by fear. No mistakes.",
"9_5" : "His sincerity is the cord that binds the hearts of others to his. He holds wealth who holds the hearts of others.",
"9_6" : "The needed rain finally pours down, bringing a well-earned time of rest. It is Nature's time to enrich the crops, so leave it to her. To work the fields in the rain and mud would only undo all good effort. Do not seek more; the gibbous moon seeks to be full, but once full can do nothing but wane",
"10_1" : "He treads the simple path of least resistance, making swift and blameless progress.",
"10_2" : "A man of modest independence treads a smooth and level path. Good fortune if you stay on course.",
"10_3" : "A one-eyed man may still see, a lame man may still walk, but it takes every resource to circumvent the tiger. When this tiger is stepped on he bites. Only a warrior supremely loyal to his cause would enter a battle he knows he hasn't the resources to survive.",
"10_4" : "He shows humble hesitation and breathless caution, yet still resolutely takes a necessary step on the tail of the tiger. His modest manner saves him from the bite.",
"10_5" : "Though fully aware of the danger that lies on the narrow path ahead, the man is fully committed to move forward. The future is uncertain.",
"10_6" : "At your journey's end, look back and examine the path you chose. If you find no causes for shame, only good works that make you shine, you may take this as an omen of the certainty of great reward",
"11_1" : "When the grass is pulled up the earth in which it is firmly rooted comes up with it. You share your new wealth with loved ones, creating a conduit for even greater fortune.",
"11_2" : "Despite his success, he is gentle to those who impose, he fords the icy stream between him and another, he does not forget his duties to those distant, he does not abandon his companions; he truly walks the Golden Mean.",
"11_3" : "Every plain leads to a slope. All going leads to a return. He who keeps his inner faith in the midst of oppression will persevere. Do not rail against what must be; savor fully what remains.",
"11_4" : "Instead of stretching to grasp the wealth that may rise out of reach, he stoops to help his companions climb to his level. They expect his resentment but receive only his faith and love; they no longer fear his power.",
"11_5" : "The emperor gives his blessing to his daughter's marriage to a commoner. All ranks of life benefit from this.",
"11_6" : "The wall crumbles into the moat. Such overfortification and defensiveness will cause you more loss than if you had remained totally exposed and had opened your arms to fate.",
"12_1" : "When grass is pulled up the earth in which it is firmly rooted comes up with it. He remains loyal to those who helped him, and carries them out of harm's way.",
"12_2" : "He knows better than the sycophants how to manipulate the petty rulers; but instead he keeps his integrity and remains among the oppressed.",
"12_3" : "A vague inward feeling of shame remains unrecognized but still succeeds in haunting.",
"12_4" : "He answers a Higher calling. Whether he survives or whether he falls, he will serve as the inspiration to those who will overthrow the oppressive regime.",
"12_5" : "He turns the tide of oppression, but never allows himself to rest on his laurels. With every advance, he asks himself, 'What if it should fail? What if it should fail?' He ties his strategy to the lesson of mulberry shoots.",
"12_6" : "The oppressive stagnation rots to the inevitable end that all such corruption must meet. Its compost nourishes the seeds of great joy and fortune.",
"13_1" : "Sincere affection in the open. Why should anything so deep and genuine cause embarrassment or shame?",
"13_2" : "The clan holds tightly, armed against outsiders. This inbreeds fear and cruelty, which can only give birth to strife and extinction.",
"13_3" : "You hold with unworthy allies.",
"13_4" : "He greets them cordially, but from a high vantage point with secreted weapons close at hand. His mistrust will slowly dissipate and good fortune will return.",
"13_5" : "He is drawn to another. He fights the attraction fiercely, but his later surrender brings joy.",
"13_6" : "He meets with others in the meadow. There all are in the open, none may remain hidden. No remorse",
"14_1" : "No mistakes if you stay out of harm's way. Remain conscious of dangers and difficulties, and you will have no regrets.",
"14_2" : "A large wagon for loading. You have found the perfect means for distributing and increasing your treasures.",
"14_3" : "A Prince gives his treasures freely to those who can better use them. A lesser man could not do this.",
"14_4" : "He can make the distinction between his true treasures within and the material possessions others covet.",
"14_5" : "His sincerity attracts and inspires others whom gold could not.",
"14_6" : "Heaven blesses you with good fortune. Improvement in all facets",
"15_1" : "The Superior Person is modest about his modesty, and thus may cross to the far shore. Good fortune.",
"15_2" : "Modesty that radiates This course brings good fortune.",
"15_3" : "The Superior Person modestly brings things to completion. Great success.",
"15_4" : "Progressive modesty continues to gain.",
"15_5" : "Modest yet firm resistance against an oppressor will end the aggression and win concessions.",
"15_6" : "Modesty is the best face when correcting the errors of your own allies.",
"16_1" : "Pride comes before a fall.",
"16_2" : "Firm as a rock, but only when necessary and appropriate. This course brings good fortune.",
"16_3" : "You wait for a compelling signal, yet ignore the knock at the gate. Missed opportunity breeds regret.",
"16_4" : "His music strikes a chord and wins hearts. His trust makes them true, and brings great success.",
"16_5" : "Thorough self-diagnosis of his own affliction keeps him safely from the brink of fatal error.",
"16_6" : "Compulsive enthusiasm can be set right if it learns from its mistakes.",
"17_1" : "An ending opens a new beginning. Stepping out of your sanctuary into new company will bring achievement.",
"17_2" : "Indulging the child, you lose the adult.",
"17_3" : "To find what you seek, you must leave the child and follow the adult.",
"17_4" : "Following for dishonorable reasons. Pause for clarity and a return to integrity. Once actions are sincere, you may move forward blamelessly.",
"17_5" : "The path ahead is strewn with blessings.",
"17_6" : "By virtue of your wise heart, you are followed by a leader. Come down from your mountain, and you will be rewarded with another",
"18_1" : "Correcting his father's error, a son treads dangerously close to dishonor. Yet sparing his father from blame brings good fortune in the end.",
"18_2" : "Correcting his mother's error, a son must not be too strident.",
"18_3" : "Restoring what his father damaged. Some regrets, but no great mistakes.",
"18_4" : "Tolerating the malpractices of the father will lead the son to ruin.",
"18_5" : "Setting right the father's ruins, The son receives honors.",
"18_6" : "Refusing to serve the conquerors of nations, he sets out to conquer hearts",
"19_1" : "Sharing the authority ensures cooperation. This course brings good fortune.",
"19_2" : "If you approach this matter together, good fortune is certain.",
"19_3" : "Aggressive action meets inflexible resistance. If regret leads to a softer approach, there will be no irreparable damage.",
"19_4" : "Successful or not, a sincere approach is the only course.",
"19_5" : "Your wise approach is worthy of a prince. Great fortune will result.",
"19_6" : "You approach with humble honesty and generosity. This is a superior act",
"20_1" : "You look at things like a child. This is pardonable in a lesser man, but a fatal flaw in one of your calibre.",
"20_2" : "Peeking from behind a screen may ensure your privacy, but it offers you only a partial view.",
"20_3" : "By looking back over the course of your life, you will know if this is a time for advance or retreat.",
"20_4" : "Observe the leader firsthand to decide the worthiness of the cause.",
"20_5" : "His future is shaped by the quality of his influence on others in the past. Be blameless.",
"20_6" : "He contemplates his own integrity without regard to the good or bad consequences his actions may have wrought. Stand or fall, he must be true to himself.",
"21_1" : "His feet are encased in stocks that hide his toes. Mild punishment, no blame.",
"21_2" : "A bite so deep into the meat that his nose disappears. Harsh, but no mistake.",
"21_3" : "Biting into dried meat And striking something spoiled. Uncomfortable, but no harm.",
"21_4" : "Biting into dried meat and striking a piece of metal. If you recognize the dangers, you may follow this course to good fortune.",
"21_5" : "Biting into dried meat and striking the golden arrowhead. Keeping to this perilous course will result in unexpected reward.",
"21_6" : "The wooden stocks cover his ears, making him deaf to the warnings to repent. Misfortune will deepen",
"22_1" : "Honoring his feet, he leaves his carriage to walk.",
"22_2" : "Adorning the beard to the detriment of the chin.",
"22_3" : "Graceful as the mist. Holding to this course brings blessing.",
"22_4" : "Artifice or simplicity? Two riders on winged white horses: one a bandit, the other an ardent suitor.",
"22_5" : "Your small roll of silk seems a shameful offering among the splendor of his gardens, yet it is your sincerity and perseverance that are truly prized.",
"22_6" : "Faultless grace is simple and pure",
"23_1" : "The legs of the throne are hacked away. The loyal are cut down.",
"23_2" : "The arms of the throne are split to kindling. Those closest to the leader are slashed away.",
"23_3" : "He moves among those who would overturn the throne. Discretion and a true heart are the key to survival.",
"23_4" : "The seat of the throne is ripped apart; the leader is falling. Outrageous fortune.",
"23_5" : "Others follow you like fish on a line. The tide turns as you bring order from the chaos.",
"23_6" : "Refusing fruit offered by the serpent, he gains a carriage when the snake swallows its own tail and the light is restored",
"24_1" : "Return after straying off-trail. Good fortune and no blame.",
"24_2" : "Your return is welcome. Great fortune.",
"24_3" : "Return after return after return. Risky, but never a mistake.",
"24_4" : "As the masses move on, you see a better path and return alone.",
"24_5" : "Openly admitting your mistake, you humbly and nobly return. No blame.",
"24_6" : "You have missed the opportunity for a triumphant return. You must now wait years before such an opportunity cycles your way again. Grave misfortune",
"25_1" : "A guileless nature reaps good fortune.",
"25_2" : "Plow your field for a field well-plowed, not for possible harvests. Clear the wasteland for land well-cleared, not for potential rich fields. Such guileless enterprise can't help but succeed.",
"25_3" : "An innocent man is unjustly accused of the theft of an ox taken by a drifter. His very simplicity will acquit him.",
"25_4" : "No mistakes if your aim remains true.",
"25_5" : "No medicine will treat this malady. Its cause was internal, as will be its cure.",
"25_6" : "Any action, however innocent, will bring misfortune. Stand fast.",
"26_1" : "One more step brings disaster. A halt now proves strategic.",
"26_2" : "The axles have been removed from your cart. Good reason to remain in place for the moment.",
"26_3" : "A good stallion with speed. Discipline daily, study your goal, and advance is assured.",
"26_4" : "Attaching a plank of wood to the brow of this young bull will stunt the growth of his horns. Such foresight brings great fortune.",
"26_5" : "The tusks of a gelded boar. Ominous-looking, but without purpose.",
"26_6" : "In harmony with the will of Heaven, your strength is irresistible",
"27_1" : "You ignore your own succulent dinner to crave the dish set before another. Misfortune.",
"27_2" : "Climbing steadily toward nourishment. you stray from the hill path to gather wild fruit. You wander toward disaster.",
"27_3" : "You gorge yourself on tempting sweets, devoid of nutritional value. Such heedless compulsiveness carries longlasting consequences.",
"27_4" : "Climbing to the summit to obtain nourishment for others, you are as alert as a tiger ready to spring. This is the correct path.",
"27_5" : "Unspeakable delights tempt maddeningly from the far bank. You must not cross this stream.",
"27_6" : "Others depend on you for sustenance. If you are aware of the great responsibility such a position carries, all will share good fortune. You may cross to the far shore",
"28_1" : "He cushions the objects with mats of white palm before setting them on the soft grass. Such overcaution is no mistake.",
"28_2" : "The old willow sprouts new shoots. An older man takes a young wife. Good fortune abounds.",
"28_3" : "The supporting beam is bending to its breaking point. Disaster looms.",
"28_4" : "You come to the rescue and reinforce the supporting structure. Order and good fortune is restored. But does your help carry a price?",
"28_5" : "The withered willow blossoms. An older woman takes a young husband. No blame, no praise.",
"28_6" : "Fording the flooded stream, he disappears beneath the rushing waters and never resurfaces. Misfortune through no fault of his own",
"29_1" : "Deep beneath the earth, he falls into an even deeper chasm. Perilous.",
"29_2" : "This dark pit you find yourself in is rife with traps and pitfalls. Don't scramble toward freedom, but concentrate on one small toehold at a time.",
"29_3" : "Deep, dangerous pitfalls on every side. Stand fast.",
"29_4" : "A simple meal of rice and wine, eaten from earthen bowls. This is correct.",
"29_5" : "The dark waters of this pit will rise no higher. Your greatest danger now lies in panic. Keep your wits and you will escape.",
"29_6" : "Bound with ropes, thrown into a thorn-filled chasm. For three years he is lost in this wasteland. Misfortune",
"30_1" : "Meek and uncertain, he nevertheless approaches the radiance. No mistake.",
"30_2" : "Glowing yellow warmth as if from the sun. Supreme good fortune.",
"30_3" : "Old men read the lesson in the setting sun. Beat the cymbal and sing in this life, or wail away the hours fearing death. Their choice is their fortune.",
"30_4" : "He bursts into flame, dazzles with his brilliance, spends his fuel, dies out quickly and is forgotten.",
"30_5" : "Tears of repentance flood. Enlightenment turns the tide for the better.",
"30_6" : "Sent as an instrument of justice, he transcends his station, delivering swift punishment to the perpetrators, but mercy to the misled. Faultless",
"31_1" : "He skillfully hides his excitement, but is betrayed by the twitching of his big toe.",
"31_2" : "Nervously shaking his leg shows his irresistible urge to advance. Misfortune if he does. Good fortune if he doesn't.",
"31_3" : "Restless thighs signify impatience and a lack of restraint. He has lost his center and is obsessed with another. Humiliation.",
"31_4" : "Trembling all over. Only those who truly know him would understand. Favorable if he stays on course.",
"31_5" : "Chills down the spine but no startled movements. No regrets.",
"31_6" : "A wagging tongue and working jaws. All sound and fury signifying nothing",
"32_1" : "He pledges his love too hastily, and awaits her promise in return. This stunts the natural growth of affection.",
"32_2" : "These bad feelings will pass.",
"32_3" : "He must remain constant, or the only permanence will reside in disgrace.",
"32_4" : "No game in the field.",
"32_5" : "To submit to insult is to invite injury.",
"32_6" : "Constant only in his inconstancy, even fortune is eventually exhausted.",
"33_1" : "You have reached the outlands of your retreat. To hold your advantage, fall back no further.",
"33_2" : "He lashes himself to his cause with thongs of yellow oxhide.",
"33_3" : "Though it imperils his retreat, he must provide for the safety of those who have served him loyally.",
"33_4" : "The Superior Person sees retreat as an opportunity to strengthen his position, and makes it so. The inferior person sees retreat as a defeat, and makes it so.",
"33_5" : "He makes a dignified retreat and retains control of the situation.",
"33_6" : "He retires nobly, seeing that it is for the good of all",
"34_1" : "He uses all his remaining strength to stamp his hoof and paw the ground. If his bluff is called, it will bring misfortune.",
"34_2" : "Good fortune ahead if you stay on course.",
"34_3" : "The inferior person throws all his energy toward his goal. The Superior Person makes conserving energy his goal. The ram butts into a hedge, entangling his horns.",
"34_4" : "Entanglements loosen, and a way opens through the wall that has blocked you. The opening is narrow and must be navigated with the greatest caution, or you will be stopped dead in your tracks again.",
"34_5" : "There are no threats left before you. You may set your ram free without regret.",
"34_6" : "If the ram butts into the hedge, the entangling thorns will prevent both advance and retreat. It is best to recognize this danger and avoid it",
"35_1" : "Meet their distrust with tolerance and benevolence; such graciousness will wear away any heart of stone.",
"35_2" : "You advance in sorrow, but this path leads to good fortune. Accept the boon of a wise woman.",
"35_3" : "He is chosen unanimously to carry out the will of the people. All self-doubt vanishes.",
"35_4" : "Scurrying like a mouse. Such blind panic increases the danger.",
"35_5" : "Advancing along this path will prove rewarding if you don't lose your focus with visions of success or failure.",
"35_6" : "Though politically perilous, it is wiser to put infidels within your own city walls to the sword, rather than lead a Crusade to convert faraway lands",
"36_1" : "The pheasant's wings falter and droop from exhaustion. The man wanders three days without eating. He goes where he must, though scorn awaits him.",
"36_2" : "The grieving pheasant has a wounded left wing. The agent of darkness wounds the man in his left thigh. Still the man helps others to safety with the strength of a horse.",
"36_3" : "The wounded pheasant hesitates outside the grain-filled cage. The man chases the agent of darkness back into the night, risking his own safety in the shadowy domain.",
"36_4" : "The pheasant senses danger and flees the jaws of the trap. Descending into the belly of the beast, the man beholds the true face of evil. In revulsion and despair, he flees what he knows he can never defeat.",
"36_5" : "The wounded pheasant is captured. Despite its fright, this is a turn for the better.",
"36_6" : "Its broken wing mended, the pheasant is released to its fate. Realizing that darkness co-exists with the light in his own heart, the man transcends the bonds of good and evil, and freely roams the heights of Heaven and the bowels of Hell",
"37_1" : "The father firmly enforces the rules that protect his family. No fault.",
"37_2" : "The neglected wife resists temptation and returns to her family duties. For her, things will improve.",
"37_3" : "Tempers are unleashed within the family. The father carries a heavy burden of guilt. If his wife or children taunt him, this will only perpetuate the cycle.",
"37_4" : "She is the jewel of the home, the family's greatest blessing.",
"37_5" : "A good ruler tempers justice with mercy. This is best for a household as well.",
"37_6" : "He sincerely wants to be fair. This brings respect to the father",
"38_1" : "Don't search after the horses you've lost; They will return in seven days. Acknowledge the presence of evil people: keep a close eye on them, but don't be baited into dealing with them.",
"38_2" : "He meets his lord in a narrow alleyway. Though he gets in the way, no harm is done.",
"38_3" : "Bandits stop his oxen team and board his wagon. He is scalped, his face is disfigured, and he is left to die. Not only will he survive -- he will endure and triumph.",
"38_4" : "Resolving to stand alone in his beliefs if he must, he is immediately joined by a kindred spirit.",
"38_5" : "A kindred spirit cuts through the barriers that separate you. Can you cross the small distance remaining?",
"38_6" : "After long isolation and persecution, he sees even the one who loves him as a beast or demon. If he will lay down his arms, they can advance toward good fortune together, through nothing more than a gentle rain",
"39_1" : "Advance will meet with opposition; Remaining in place will meet with praise.",
"39_2" : "He stoically faces trial after trial, knowing his loyal labors will benefit another.",
"39_3" : "Advance will meet with breathtaking obstacles. Remaining will meet with criticism from family and friends.",
"39_4" : "Advance alone against insurmountable odds, or remain in place, gathering strength and allies.",
"39_5" : "On the brink of crushing defeat, friends come to the rescue.",
"39_6" : "Advance will meet with disastrous difficulties. What you seek is right at hand. Ask guidance from someone you respect",
"40_1" : "There has been no mistake. You are not at fault.",
"40_2" : "He kills three foxes in the hunt and wins the golden arrow. Great fortune if you follow this course.",
"40_3" : "The porter carries his burden in a gilded carriage well beyond his means. This attracts not only the resentment of his peers, but bandits as well. Injury and humiliation ahead.",
"40_4" : "Free yourself from this useless dependence. A new and trustworthy companion will appear.",
"40_5" : "He escapes the traps set by inferior men, then treats the conspirators as comrades. By making them friends, he rids himself of enemies.",
"40_6" : "He calmly lifts his bow and picks off a falcon atop a distant tower. Such prowess breaks the spirit of his challengers. Nothing but good fortune from this point",
"41_1" : "Once your good work is accomplished, it is noble to move quietly on. But your charges have grown attached to you, and will feel a deep loss if you go.",
"41_2" : "You are able to provide what others need without depriving yourself. Keep to this humble course of aid, but do not attempt a heroic rescue, or unforeseen calamities will fall.",
"41_3" : "When three travel together, two will bond more closely, slighting the third. If one journeys alone, he will meet a fellow seeker.",
"41_4" : "Once he recognizes and admits his wound, walls tumble down and others can get through to offer the balm he needs for healing.",
"41_5" : "He is showered with precious gifts, and those giving will hear no refusals. Supreme good fortune.",
"41_6" : "He finds gain in that which others see no value. His example generates widespread support. This course brings success",
"42_1" : "The forces of the cosmos are cycling in your favor. This is an ideal time for great progress and expansion in every endeavor.",
"42_2" : "Your work is reverently admired by another who makes a substantial contribution to your cause. This patron is deeply spiritual, and can benefit you in ways beyond the material world.",
"42_3" : "You are enriched by another's misfortune. This is no basis for guilt or shame; you did nothing to bring on these events.",
"42_4" : "Your balance and skill have not gone unnoticed by those in power. They will entrust you with responsibilities that have far-reaching influence.",
"42_5" : "Your benevolence has been recognized by those above you. Your plans will greatly benefit all, and the favor you seek is as good as granted before you even ask.",
"42_6" : "Your heart isn't in it, and others can sense this. Every move you make is watched with suspicion. Steel your resolve, or failure is certain",
"43_1" : "Though you feel confident, you are not equal to the overwhelming odds you face. One step forward will set you back a mile.",
"43_2" : "An anguished cry pierces the night. Fully armed, sleepless and ever-watchful, but there is no need for fear.",
"43_3" : "Keep a tight lock on your mouth. It takes resolve to face the insults silently, but they will prove harmless, and others will gradually warm to your sense of dignity.",
"43_4" : "Your legs are torn and bleeding as you push heedlessly through the thorns toward your target. If you would allow yourself to be led down the path of least resistance, you would reach your goal.",
"43_5" : "The wisest method for dealing with weeds is to remove them before they are firmly rooted. In this way, your garden grows strong without violence.",
"43_6" : "A warning sign goes unheeded. Misfortune ahead",
"44_1" : "Get control of yourself. This temptation has you rooting like a hog. Only self-discipline can steer you off this road to disaster.",
"44_2" : "A fish in the kitchen. Adequate for your humble needs, but not suitable for guests. No mistake.",
"44_3" : "They flay the skin from his thighs then toss him in the wasteland to struggle home. He will live to remember this hideous lesson, and will avoid any more painful mistakes.",
"44_4" : "No fish for guests; none even for yourself. Misfortune.",
"44_5" : "Keep this melon growing in the shade. It is a blessing from heaven.",
"44_6" : "You lower your horns toward one who sincerely wants to become close to you. Your companion's understanding will spare you any regret.",
"45_1" : "You seem to blow both hot and cold, sometimes seeking to join in, sometimes shrinking away. Admit your fears out loud, and a true companion will answer. Joy returns.",
"45_2" : "It will prove good fortune to allow yourself to be drawn into this group. Attract an invitation by having something small but sincere to offer.",
"45_3" : "You strive to find common ground that doesn't exist. Sighing in sadness and walking away would be understood, though you may think less of yourself.",
"45_4" : "No one will begrudge you the good fortune ahead.",
"45_5" : "You are in a position to bring people together and lead them. At first there will be doubters and detractors, but your calm resolve will win even their hearts.",
"45_6" : "A gathering of mourners. No one is to blame",
"46_1" : "You rise to a level where you are made welcome as a peer.",
"46_2" : "Even a small offering is appreciated, if it is sincere.",
"46_3" : "You have risen to become ruler of an empty city.",
"46_4" : "The king continues to faithfully climb Mount Chi and make humble offering.",
"46_5" : "Climb these steps to good fortune.",
"46_6" : "Climbing onward and upward through dark of night is perilous, but your tenacity is admirable. Good fortune if you avoid the slightest misstep",
"47_1" : "He rests beneath a dead tree, trying to make sense of this dark, desolate valley he has strayed into. These lost wanderings will last three years.",
"47_2" : "Chained to the banquet table, a prisoner of his own rich tastes. He offers prayer and sacrifice for delivery from desire. When even the desire to be delivered has been cleansed, his prayers will have been answered.",
"47_3" : "Hemmed in by stone, with nothing to climb but thorns: a trap of his own making. Struggling home, he cannot find his wife. Misfortune.",
"47_4" : "Captive and on display in a golden carriage, he is ashamed of the spectacle he has become. Such regrets will lead to good fortune.",
"47_5" : "Though his nose and feet will surely be cut off, still he must confront the warlord. He calmly accepts his fate, and offers prayer and sacrifice.",
"47_6" : "He feels tightly bound by no more than a few vines of ivy. If he firmly resolves to break free, he will find he was held back by only his own guilt and fear",
"48_1" : "The water in this old well has seeped into the mud. Not even the animals come to drink from it.",
"48_2" : "Shooting at fish in the well puts holes in the bucket. No one can draw from this well.",
"48_3" : "This well has been cleansed, but no one will drink from it. This is a tragic mistake, for it has much to offer prince and pauper alike.",
"48_4" : "The well is carefully retiled, and in time made pure again.",
"48_5" : "The water in this well comes from a cool, deep, inexhaustible spring.",
"48_6" : "This well is dependable and available to all. Supreme good fortune",
"49_1" : "Bound with bands of yellow oxhide.",
"49_2" : "When the time is ripe, you will be the instrument of change. Plant the seeds of revolution now, and success is assured.",
"49_3" : "Premature action would prove disastrous. Let the talk of revolution ferment among the people. When the rumors have reached your ear three times, that is your signal to strike.",
"49_4" : "Your honor is redeemed. All impediments fall away and the path ahead is clear.",
"49_5" : "You transform into a tiger before their eyes. Your very being commands an awe that makes consulting the oracle unnecessary.",
"49_6" : "You dodge the snares and snatch victory with the lightning speed and agility of a panther. The jackals lose their nerve and swear allegiance to you. You have won your revolt. Don't seek to climb higher. Instead stabilize the new order for the good of all",
"50_1" : "Tip over the caldron and get rid of its stagnant contents once and for all. He marries a woman to give her children a home. Blameless.",
"50_2" : "Your caldron contains a hearty meal with plenty to go around. Your rivals are jealous of your ability to provide, but they can't harm you. Good fortune.",
"50_3" : "You cooked a perfect meal in a caldron you can't lift from the fire. The feast is wasted. Once the storm of resentment has washed over you, good fortune will come again.",
"50_4" : "A leg of the caldron buckles, spilling the hot meal on the very person you wish to serve. Trust evaporates, and the void is filled with shame and scorn.",
"50_5" : "The caldron you cook in has yellow handles and golden carrying rings. Good fortune if you keep to this course.",
"50_6" : "Your caldron is fitted with jade handles. Great success in whatever you do.",
"51_1" : "The thunderclap rips screams of terror from the hearts of all below. After its last echo, only nervous laughter can be heard. All is well.",
"51_2" : "This thunder erupts from the ground beneath your feet, delivering real danger. Abandon your belongings and climb to higher ground. Don't grieve over treasures left behind. They will return to you in seven days.",
"51_3" : "These deafening thunderclaps will roll on eastward. If they shock you into action, though, their passing will have left a permanent change for the good.",
"51_4" : "If you run in blind terror from this thunder, you will end up hopelessly mired in the mud.",
"51_5" : "Others run in confusion and terror from the violent thunderstorm. Fully aware of the danger, you keep to the task that must be done.",
"51_6" : "The lightning teeth of the thunder above and the yawning jaws of the earthquake below wreak havoc and ruin on neighbors around you, while you remain miraculously untouched. There will be rumors and accusations. Don't react, or their fate will become yours",
"52_1" : "Not even moving a toe. No mistakes. Hold to this course.",
"52_2" : "Relaxing his legs. He sees he cannot rescue the one he follows. He resigns himself to sorrow.",
"52_3" : "He seeks stillness through rigidity instead of relaxation. He will paralyze his legs and overtax his heart.",
"52_4" : "He keeps his trunk still through flexibility. Faultless.",
"52_5" : "Keeping his jaw relaxed, what words he speaks carry order and deliberation. Conflict dissolves.",
"52_6" : "His constant goal is an end to striving. Good fortune",
"53_1" : "The wild geese draw near shore. The inexperience and brashness of youth may lead to danger, but a sharp warning will set things right.",
"53_2" : "The geese draw near the cliff. There will be feasting, peace, rest and joy.",
"53_3" : "The wild geese nest in the open prairie. The male leaves to forage; he will not return. The brooding female will not hatch her young. Predators close in.",
"53_4" : "The wild geese must find shelter in the trees. Only the broadest, flattest branches will harbor them. No mishaps.",
"53_5" : "The wild geese draw near the summit. For three years the female has borne no young; now nothing will stop her. Deliverance.",
"53_6" : "The wild geese fly to a home above the clouds. They no longer need their feathers, and leave them behind for the sacred dance. Peace everlasting",
"54_1" : "Even becoming a concubine would be an advance in this woman's life. For the lame, any step forward is a good step.",
"54_2" : "Left alone in her marriage, she remains content in her illusions. Sometimes a one-eyed man is blessed for what he can't see.",
"54_3" : "Not fulfilled by her marriage, the young woman returns home to her former life.",
"54_4" : "The maiden waits far longer than seems wise, to make sure her marriage is right.",
"54_5" : "The princess bride dresses humbly, out of respect for her commoner groom. Her bridesmaids outshine her by far. She is a treasure.",
"54_6" : "The groom draws no blood from the sacrifice. The bride's basket remains empty. A barren marriage",
"55_1" : "He meets his soulmate, and they couple ceaselessly for ten days. No mistake. This union will change worlds.",
"55_2" : "The veil before his eyes casts so dark a shade, he sees the Big Dipper at noontime. Authorities distrust one with such vision. It is best to emphasize why seeing the truth is the safest route to preserving power.",
"55_3" : "The veil before his eyes casts so dark a shade, he can see the smallest stars at noontime. For such vision, he loses the use of his right arm. No mistake.",
"55_4" : "The veil before his eyes casts so dark a shade, he can see the polestar at noontime. It leads him to his soulmate. No mistake.",
"55_5" : "He attracts the brilliant and able to his quest. Good fortune.",
"55_6" : "In his large and splendid house, no friends or family dwell. He sees no one pass through his gate for three years. Misfortune",
"56_1" : "A traveler with petty complaints and too many demands soon wears out his welcome.",
"56_2" : "The traveler lodges at an inn and keeps his belongings with him at all times. He gains a loyal servant.",
"56_3" : "The traveler causes a fire that burns down the inn. He loses the trust of his servant and traveling companions. Danger.",
"56_4" : "Taking shelter in an abandoned cabin, the traveler finds his stolen belongings beside a razor-sharp axe. What should be delight freezes to dread.",
"56_5" : "The traveler kills a pheasant with his first shot. For the price of one arrow, he has bought himself praise and high office.",
"56_6" : "The traveler uses a bird's nest as kindling. He chuckles at his cleverness, but soon weeps when he loses his ox. Misfortune",
"57_1" : "Advance or retreat: the determined warrior will use either to advantage.",
"57_2" : "A whirlwind beneath the bed. Fortunetellers and magicians are summoned, but none can interpret this omen. All will go well.",
"57_3" : "Half-hearted attempts to penetrate, over and over again. Humiliation.",
"57_4" : "Self-doubt vanishes and determination grows. Three forms of game will be taken in this hunt.",
"57_5" : "Determination has settled into a steady course toward good fortune. That was no way to start, but it will lead to a glorious ending. Consider any crossroad three days before pressing on. Check your bearings for three days following, to ensure you haven't strayed from your course.",
"57_6" : "The wind dies beneath the bed. All courage to persevere is gone. Resources are depleted, defenses are down. To move ahead with this course would prove disastrous",
"58_1" : "Harmony and quiet words. Joyous contentment. Good fortune.",
"58_2" : "Rejoice in his sincerity. This good fortune will last into the future, if you don't let the past resurface.",
"58_3" : "Arguing and negotiating to win love and joy. Self-defeat. Misfortune.",
"58_4" : "This experimentation with diverse pleasures, this fruitless chase after the ultimate thrill, will damage you. Joy is tranquil, not mad rushing, and will arise from peace.",
"58_5" : "You place your trust in an unworthy ally.",
"58_6" : "Don't let thrill-seeking comrades divert you from true joy",
"59_1" : "He gives aid with the strength and stamina of a horse. Good fortune.",
"59_2" : "When his dreams evaporate to mist on the breeze, he returns to his well of strength. Regret is washed away.",
"59_3" : "His ego dissolves and the void is filled with his Self. No more fear and frustration.",
"59_4" : "He scatters his group far and wide. Those who return will be of firmer resolve and leaner, stronger fibre. An ingenious move.",
"59_5" : "He cries in pain as he sweats out this fever. The king opens the royal stockpile to his subjects. No mistake.",
"59_6" : "He follows the trail of his own blood to safety",
"60_1" : "Roaming his own garden and courtyard, he never strays out the gate. No mistake.",
"60_2" : "Pacing his own garden and courtyard, he refuses to pass out the gate. Misfortune.",
"60_3" : "He without self-restraint today forges the shackles that hobble him tomorrow.",
"60_4" : "He is most content in frugality and simplicity: the highest success.",
"60_5" : "He travels easily with economy and simplicity. This brings merit.",
"60_6" : "Self-discipline teetering toward self-destruction. An empty martyrdom. Turn back",
"61_1" : "The wading heron releases all desire, so that a passing fish will reward him with lunch.",
"61_2" : "A crane calls from the shade and her young answer with love. My cup of life is filled to the brim. Come share it with me.",
"61_3" : "True companions share their fate. One beats the drum, one grows silent. One weeps, one sings.",
"61_4" : "Just before the moon waxes full, One horse breaks from the harness, and its mate remains. It is as it should be.",
"61_5" : "Finding himself, his serene inner flame radiates warmth that draws others near. He does not Do; he just Is.",
"61_6" : "This cock's crow pierces to Heaven. A warning best heeded.",
"62_1" : "It is perilous for so small a bird to fly so high.",
"62_2" : "She invokes the spirit of her ancestor, but is visited by her ancestress. He heads straight for the Prince but is intercepted by the Minister. It is best.",
"62_3" : "Focusing so intensely on your target has given you tunnel vision. An ambush could reach you from three sides. Heed this warning.",
"62_4" : "This prize you have strived for could be the end of you. Wake up to its danger and you will prevail.",
"62_5" : "Don't take shelter from storms that have not yet blown in. It is too easy to shoot a bird in a cave.",
"62_6" : "He flies too high, beyond his limit. The plummet to earth is spent lamenting",
"63_1" : "The man brakes his wheels, but the fox leaps the stream, wetting his tail just short of safety. No harm.",
"63_2" : "The woman has lost her screen. She will remain exposed seven days before it is returned.",
"63_3" : "He marches into the Devil's Domain, and conquers it after three grueling years. Lesser men could not do this.",
"63_4" : "The finest clothes can be shredded to rags. Keep a sharp eye on the discontent.",
"63_5" : "The sacrificial festival launched by his eastern neighbor cannot overshadow the western man's simple, sincere offering.",
"63_6" : "His head disappears beneath the waves. Danger",
"64_1" : "Careless so near to shore, the fox gets his tail wet. Humiliation.",
"64_2" : "He brakes his wheels, but remains on the path. Good fortune.",
"64_3" : "Though the far shore is in sight, eagerness invites carelessness. Cross the river before stepping out of the boat.",
"64_4" : "Deep in the Devil's Domain, there is no room for despair. Persevere for three years, and victory will be yours.",
"64_5" : "True to himself to the end, inner light radiates from him and warms others in the glow. Good fortune.",
"64_6" : "Too much wine at the victory feast can remove all cause for celebration. Be a good winner."
}]
