var hexagrams = [{
"111111": {"definition": "01. Force (乾 qián); The Creative; Possessing Creative Power & Skill",
            "hexagram": "䷀",
            "number": "1",
            "x": ""},
  "000000": {"definition": "02. Field (坤 kūn); The Receptive; Needing Knowledge & Skill; Do not force matters and go with the flow",
            "hexagram": "䷁",
            "number": "2",
            "x": ""},
  "100010": {"definition": "03. Sprouting (屯 zhūn); Difficulty at the Beginning; Sprouting ",
            "hexagram": "䷂",
            "number": "3",
            "x": ""},
  "010001": {"definition": "04. Enveloping (蒙 méng); Youthful Folly; Detained, Enveloped and Inexperienced",
            "hexagram": "䷃",
            "number": "4",
            "x": ""},
  "111010": {"definition": "05. Attending (需 xū); Waiting; Uninvolvement (Wait for now), Nourishment ",
            "hexagram": "䷄",
            "number": "5",
            "x": ""},
  "010111": {"definition": "06. Arguing (訟 sòng); Conflict; Engagement in Conflict ",
            "hexagram": "䷅",
            "number": "6",
            "x": ""},
  "010000": {"definition": "07. Leading (師 shī); The Army; Bringing Together, Teamwork ",
            "hexagram": "䷆",
            "number": "7",
            "x": ""},
  "000010": {"definition": "08. Grouping (比 bǐ); Holding Together; Union ",
            "hexagram": "䷇",
            "number": "8",
            "x": ""},
  "111011": {"definition": "09. Small Accumulating (小畜 xiǎo chù); Small Taming; Accumulating Resources",
            "hexagram": "䷈",
            "number": "9",
            "x": ""},
  "110111": {"definition": "10. Treading (履 lǚ); Treading (Conduct); Continuing with Alertness",
            "hexagram": "䷉",
            "number": "10",
            "x": ""},
  "111000": {"definition": "11. Pervading (泰 tài); Peace; Pervading",
            "hexagram": "䷊",
            "number": "11",
            "x": ""},
  "000111": {"definition": "12. Obstruction (否 pǐ); Standstill; Stagnation",
            "hexagram": "䷋",
            "number": "12",
            "x": ""},
  "101111": {"definition": "13. Concording People (同人 tóng rén); Fellowship; Fellowship, Partnership",
            "hexagram": "䷌",
            "number": "13",
            "x": ""},
  "111101": {"definition": "14. Great Possessing (大有 dà yǒu); Great Possession; Independence, Freedom",
            "hexagram": "䷍",
            "number": "14",
            "x": ""},
  "001000": {"definition": "15. Humbling (謙 qiān); Modesty; Being Reserved, Refraining",
            "hexagram": "䷎",
            "number": "15",
            "x": ""},
  "000100": {"definition": "16. Providing-For (豫 yù); Enthusiasm; Inducement, New Stimulus",
            "hexagram": "䷏",
            "number": "16",
            "x": ""},
  "100110": {"definition": "17. Following (隨 suí); Following; Following",
            "hexagram": "䷐",
            "number": "17",
            "x": ""},
  "011001": {"definition": "18. Corrupting (蠱 gǔ); Work on the Decayed; Repairing",
            "hexagram": "䷑",
            "number": "18",
            "x": ""},
  "110000": {"definition": "19. Nearing (臨 lín); Approach; Approaching Goal, Arriving ",
            "hexagram": "䷒",
            "number": "19",
            "x": ""},
  "000011": {"definition": "20. Viewing (觀 guān); Contemplation; The Withholding",
            "hexagram": "䷓",
            "number": "20",
            "x": ""},
  "100101": {"definition": "21. Gnawing Bite (噬嗑 shì kè); Biting Through; Deciding",
            "hexagram": "䷔",
            "number": "21",
            "x": ""},
  "101001": {"definition": "22. Adorning (賁 bì); Grace; Embellishing",
            "hexagram": "䷕",
            "number": "22",
            "x": ""},
  "000001": {"definition": "23. Stripping (剝 bō); Splitting Apart; Stripping, Flaying",
            "hexagram": "䷖",
            "number": "23",
            "x": ""},
  "100000": {"definition": "24. Returning (復 fù); Return; Returning",
            "hexagram": "䷗",
            "number": "24",
            "x": ""},
  "100111": {"definition": "25. Without Embroiling (無妄 wú wàng); Innocence; Without Rashness",
            "hexagram": "䷘",
            "number": "25",
            "x": ""},
  "111001": {"definition": "26. Great Accumulating (大畜 dà chù); Great Taming; Accumulating Wisdom",
            "hexagram": "䷙",
            "number": "26",
            "x": ""},
  "100001": {"definition": "27. Swallowing (頤 yí); Mouth Corners; Seeking Nourishment",
            "hexagram": "䷚",
            "number": "27",
            "x": ""},
  "011110": {"definition": "28. Great Exceeding (大過 dà guò); Great Preponderance; Great Surpassing",
            "hexagram": "䷛",
            "number": "28",
            "x": ""},
  "010010": {"definition": "29. Gorge (坎 kǎn); The Abysmal Water; Darkness, Gorge",
            "hexagram": "䷜",
            "number": "29",
            "x": ""},
  "101101": {"definition": "30. Radiance (離 lí); The Clinging; Clinging, Attachment",
            "hexagram": "䷝",
            "number": "30",
            "x": ""},
  "001110": {"definition": "31. Conjoining (咸 xián); Influence; Attraction",
            "hexagram": "䷞",
            "number": "31",
            "x": ""},
  "011100": {"definition": "32. Persevering (恆 héng); Duration; Perseverance",
            "hexagram": "䷟",
            "number": "32",
            "x": ""},
  "001111": {"definition": "33. Retiring (遯 dùn); Retreat; Withdrawing",
            "hexagram": "䷠",
            "number": "33",
            "x": ""},
  "111100": {"definition": "34. Great Invigorating (大壯 dà zhuàng); Great Power; Great Boldness",
            "hexagram": "䷡",
            "number": "34",
            "x": ""},
  "000101": {"definition": "35. Prospering (晉 jìn); Progress; Expansion, Promotion",
            "hexagram": "䷢",
            "number": "35",
            "x": ""},
  "101000": {"definition": "36. Brightness Hiding (明夷 míng yí); Darkening of the Light; Brilliance Injured",
            "hexagram": "䷣",
            "number": "36",
            "x": ""},
  "101011": {"definition": "37. Dwelling People (家人 jiā rén); The Family; Family",
            "hexagram": "䷤",
            "number": "37",
            "x": ""},
  "110101": {"definition": "38. Polarising (睽 kuí); Opposition; Division, Divergence",
            "hexagram": "䷥",
            "number": "38",
            "x": ""},
  "001010": {"definition": "39. Limping (蹇 jiǎn); Obstruction; Halting, Hardship",
            "hexagram": "䷦",
            "number": "39",
            "x": ""},
  "010100": {"definition": "40. Taking-Apart (解 xiè); Deliverance; Liberation, Solution",
            "hexagram": "䷧",
            "number": "40",
            "x": ""},
  "110001": {"definition": "41. Diminishing (損 sǔn); Decrease; Decrease",
            "hexagram": "䷨",
            "number": "41",
            "x": ""},
  "100011": {"definition": "42. Augmenting (益 yì); Increase; Increase",
            "hexagram": "䷩",
            "number": "42",
            "x": ""},
  "111110": {"definition": "43. Parting (夬 guài); Breakthrough; Separation",
            "hexagram": "䷪",
            "number": "43",
            "x": ""},
  "011111": {"definition": "44. Coupling (姤 gòu); Coming to Meet; Encountering",
            "hexagram": "䷫",
            "number": "44",
            "x": ""},
  "000110": {"definition": "45. Clustering (萃 cuì); Gathering Together; Association, Companionship",
            "hexagram": "䷬",
            "number": "45",
            "x": ""},
  "011000": {"definition": "46. Ascending (升 shēng); Pushing Upward; Growing Upward",
            "hexagram": "䷭",
            "number": "46",
            "x": ""},
  "010110": {"definition": "47. Confining (困 kùn); Oppression; Exhaustion",
            "hexagram": "䷮",
            "number": "47",
            "x": ""},
  "011010": {"definition": "48. Welling (井 jǐng); The Well; Replenishing, Renewal",
            "hexagram": "䷯",
            "number": "48",
            "x": ""},
  "101110": {"definition": "49. Skinning (革 gé); Revolution; Abolishing the Old",
            "hexagram": "䷰",
            "number": "49",
            "x": ""},
  "011101": {"definition": "50. Holding (鼎 dǐng); The Cauldron; Establishing the New",
            "hexagram": "䷱",
            "number": "50",
            "x": ""},
  "100100": {"definition": "51. Shake (震 zhèn); Arousing; Mobilizing",
            "hexagram": "䷲",
            "number": "51",
            "x": ""},
  "001001": {"definition": "52. Bound (艮 gèn); The Keeping Still; Immobility",
            "hexagram": "䷳",
            "number": "52",
            "x": ""},
  "001011": {"definition": "53. Infiltrating (漸 jiàn); Development; Auspicious Outlook, Infiltration",
            "hexagram": "䷴",
            "number": "53",
            "x": ""},
  "110100": {"definition": "54. Converting The Maiden (歸妹 guī mèi); The Marrying Maiden; Marrying",
            "hexagram": "䷵",
            "number": "54",
            "x": ""},
  "101100": {"definition": "55. Abounding (豐 fēng); Abundance; Goal Reached,Ambition Achieved",
            "hexagram": "䷶",
            "number": "55",
            "x": ""},
  "001101": {"definition": "56. Sojourning (旅 lǚ); The Wanderer; Travel",
            "hexagram": "䷷",
            "number": "56",
            "x": ""},
  "011011": {"definition": "57. Ground (巽 xùn); The Gentle; Subtle Influence",
            "hexagram": "䷸",
            "number": "57",
            "x": ""},
  "110110": {"definition": "58. Open (兌 duì); The Joyous; Overt Influence",
            "hexagram": "䷹",
            "number": "58",
            "x": ""},
  "010011": {"definition": "59. Dispersing (渙 huàn); Dispersion; Dispersal",
            "hexagram": "䷺",
            "number": "59",
            "x": ""},
  "110010": {"definition": "60. Articulating (節 jié); Limitation; Discipline",
            "hexagram": "䷻",
            "number": "60",
            "x": ""},
  "110011": {"definition": "61. Centre Confirming (中孚 zhōng fú); Inner Truth; Staying Focused,Avoid Misrepresentation",
            "hexagram": "䷼",
            "number": "61",
            "x": ""},
  "001100": {"definition": "62. Small Exceeding (小過 xiǎo guò); Small Preponderance; Small Surpassing",
            "hexagram": "䷽",
            "number": "62",
            "x": ""},
  "101010": {"definition": "63. Already_Fording (既濟 jì jì); After Completion; Completion",
            "hexagram": "䷾",
            "number": "63",
            "x": ""},
  "010101": {"definition": "64. Not-Yet Fording (未濟 wèi jì); Before Completion; Incompletion",
            "hexagram": "䷿",
            "number": "64",
            "x": ""}
}]
